const ICEMAN_ML = 'https://www.mercadolivre.com.br/loja/iceman';
const ICEMAN_SHOPEE = 'https://shopee.com.br/icemanoficial';
const ICEMAN_ML_PRODUCTS = {
  '695':'https://produto.mercadolivre.com.br/MLB-6976153758',
  '765':'https://produto.mercadolivre.com.br/MLB-4265643961',
  '139':'https://produto.mercadolivre.com.br/MLB-4658555814',
  '612':'https://produto.mercadolivre.com.br/MLB-6976153606',
  '468':'https://produto.mercadolivre.com.br/MLB-5294628944',
  '344':'https://produto.mercadolivre.com.br/MLB-4686080780',
  '274':'https://produto.mercadolivre.com.br/MLB-5826134548',
  '253':'https://produto.mercadolivre.com.br/MLB-4645113625',
  '474':'https://produto.mercadolivre.com.br/MLB-3697931615',
  '881F':'https://produto.mercadolivre.com.br/MLB-3694508657',
  '834':'https://produto.mercadolivre.com.br/MLB-5317240892',
  '476':'https://produto.mercadolivre.com.br/MLB-5917599488',
  'ciclismo':'https://produto.mercadolivre.com.br/MLB-5832739536'
};
const ICEMAN_SHOPEE_PRODUCTS = {
  '765':'https://shopee.com.br/product/1449173395/19499598860',
  '139':'https://shopee.com.br/product/1449173395/22394319184',
  '612':'https://shopee.com.br/product/1449173395/58201868527',
  '468':'https://shopee.com.br/product/1449173395/58201872414',
  '274':'https://shopee.com.br/product/1449173395/22299266239',
  '253':'https://shopee.com.br/product/1449173395/58252313218',
  '474':'https://shopee.com.br/product/1449173395/22298777744',
  '834':'https://shopee.com.br/product/1449173395/23093678162',
  '476':'https://shopee.com.br/product/1449173395/23093678142'
};
window.ICEMAN_CATALOG = { products: [
  { id:'695', name:'ICEMAN 695', label:'Polarizado • Meio aro', description:'Um clássico de linhas marcantes, com lentes polarizadas e proteção UV400.', details:['Lentes polarizadas','Proteção UV400','Formato meio aro','5 variações de cor'], colors:[{name:'Preto / Lente Preta',hex:'#111315',image:'../products/695/01-preto-lente-preta.png'},{name:'Tartaruga / Lente Verde',hex:'#596d5d',image:'../products/695/02-tartaruga-lente-verde.png'},{name:'Preto / Lente Verde',hex:'#405849',image:'../products/695/03-preto-lente-verde.png'},{name:'Marrom / Lente Marrom',hex:'#70412f',image:'../products/695/04-marrom-lente-marrom.png'},{name:'Tartaruga / Lente Marrom',hex:'#8a5a35',image:'../products/695/05-tartaruga-lente-marrom.png'}], images:['../products/695/01-preto-lente-preta.png','../products/695/02-tartaruga-lente-verde.png','../products/695/03-preto-lente-verde.png','../products/695/04-marrom-lente-marrom.png','../products/695/05-tartaruga-lente-marrom.png'], ml:ICEMAN_ML, shopee:ICEMAN_SHOPEE },
  { id:'765', name:'ICEMAN 765', label:'Polarizado • Urbano', description:'Design quadrado e leve para acompanhar a rotina com conforto e proteção.', details:['Lentes polarizadas','Proteção UV400','Policarbonato','7 variações de cor'], colors:[{name:'Laranja',hex:'#e86827',image:'../products/765/01-laranja.png'},{name:'Preto (Liso)',hex:'#111315',image:'../products/765/02-preto-liso.png'},{name:'Preto (C/ Desenho)',hex:'#263f56',image:'../products/765/03-preto-com-desenho.png'},{name:'Azul',hex:'#26a7de',image:'../products/765/04-azul.png'},{name:'Verde',hex:'#36b864',image:'../products/765/05-verde.png'},{name:'Amarelo',hex:'#e7cd42',image:'../products/765/06-amarelo.png'},{name:'Fotocrômico',hex:'#b8bdc1',image:'../products/765/07-fotocromico.png'}], images:['../products/765/01-laranja.png','../products/765/02-preto-liso.png','../products/765/03-preto-com-desenho.png','../products/765/04-azul.png','../products/765/05-verde.png','../products/765/06-amarelo.png','../products/765/07-fotocromico.png'], ml:ICEMAN_ML, shopee:ICEMAN_SHOPEE },
  { id:'139', name:'ICEMAN 139', label:'Polarizado • Aviador militar', description:'Aviador quadrado de inspiração militar, com armação metálica e acabamento sofisticado.', details:['Lentes polarizadas','Proteção UV400','Armação metálica','3 variações de cor'], colors:[{name:'Prateado',hex:'#b5bbc0',image:'../products/139/01-prateado.png'},{name:'Preto',hex:'#111315',image:'../products/139/02-preto.png'},{name:'Dourado',hex:'#c8a263',image:'../products/139/03-dourado.png'}], images:['../products/139/01-prateado.png','../products/139/02-preto.png','../products/139/03-dourado.png'], ml:ICEMAN_ML, shopee:ICEMAN_SHOPEE },
  { id:'612', name:'ICEMAN 612', label:'Polarizado • Aviador', description:'Aviador grande com mola nas hastes, lentes polarizadas e proteção UV400.', details:['Lentes polarizadas','Proteção UV400','Armação metálica','3 variações de cor'], colors:[{name:'Cinza Chumbo',hex:'#555b61',image:'../products/612/01-cinza-chumbo.png'},{name:'Prateado',hex:'#b7bdc2',image:'../products/612/02-prateado.png'},{name:'Preto',hex:'#111315',image:'../products/612/03-preto.png'}], images:['../products/612/01-cinza-chumbo.png','../products/612/02-prateado.png','../products/612/03-preto.png'], ml:ICEMAN_ML, shopee:ICEMAN_SHOPEE },
  { id:'468', name:'ICEMAN 468', label:'Polarizado • Aviador', description:'Aviador metálico clássico com cinco acabamentos, incluindo opções fotocrômicas.', details:['Proteção UV400','Armação metálica','Formato aviador','5 variações de cor'], colors:[{name:'Marrom',hex:'#744632',image:'../products/468/01-marrom.png'},{name:'Preto',hex:'#111315',image:'../products/468/02-preto.png'},{name:'Prateado',hex:'#b9bec2',image:'../products/468/03-prateado.png'},{name:'Amarelo Fotocrômico',hex:'#e4c33e',image:'../products/468/04-amarelo-fotocromico.png'},{name:'Preto Fotocrômico',hex:'#aeb3b7',image:'../products/468/05-preto-fotocromico.png'}], images:['../products/468/01-marrom.png','../products/468/02-preto.png','../products/468/03-prateado.png','../products/468/04-amarelo-fotocromico.png','../products/468/05-preto-fotocromico.png'], ml:ICEMAN_ML, shopee:ICEMAN_SHOPEE },
  { id:'344', name:'ICEMAN 344', label:'Polarizado • Esportivo', description:'Modelo esportivo de linhas envolventes, com armação metálica leve e lentes amplas.', details:['Lentes polarizadas','Proteção UV400','Armação metálica','2 variações de cor'], colors:[{name:'Preto',hex:'#111315',image:'../products/344/01-preto.png'},{name:'Cinza Chumbo',hex:'#5c6165',image:'../products/344/02-cinza-chumbo.png'}], images:['../products/344/01-preto.png','../products/344/02-cinza-chumbo.png'], ml:ICEMAN_ML, shopee:ICEMAN_SHOPEE },
  { id:'274', name:'ICEMAN 274', label:'Luz azul • Grau', description:'Armação leve para lentes com filtro de luz azul, disponível em cinco acabamentos.', details:['Filtro de luz azul','Lentes transparentes','Armação leve','5 variações de cor'], colors:[{name:'Preto Fosco',hex:'#242628',image:'../products/274/01-preto-fosco.png'},{name:'Azul',hex:'#255a9d',image:'../products/274/02-azul.png'},{name:'Vermelho',hex:'#8d2d32',image:'../products/274/03-vermelho.png'},{name:'Preto Brilhante',hex:'#111315',image:'../products/274/04-preto-brilhante.png'},{name:'Azul Claro',hex:'#9ab9ce',image:'../products/274/05-azul-claro.png'}], images:['../products/274/01-preto-fosco.png','../products/274/02-azul.png','../products/274/03-vermelho.png','../products/274/04-preto-brilhante.png','../products/274/05-azul-claro.png'], ml:ICEMAN_ML, shopee:ICEMAN_SHOPEE },
  { id:'253', name:'ICEMAN 253', label:'Polarizado • Quadrado', description:'Modelo quadrado marcante com seis combinações de armação, detalhes e lentes.', details:['Lentes polarizadas','Proteção UV400','Armação leve','6 variações de cor'], colors:[{name:'Azul',hex:'#239ed4',image:'../products/253/01-azul.png'},{name:'Verde',hex:'#46a77b',image:'../products/253/02-verde.png'},{name:'Transparente',hex:'#c8cdd1',image:'../products/253/03-transparente.png'},{name:'Laranja',hex:'#e9682d',image:'../products/253/04-laranja.png'},{name:'Marrom',hex:'#865539',image:'../products/253/05-marrom.png'},{name:'Preto',hex:'#111315',image:'../products/253/06-preto.png'}], images:['../products/253/01-azul.png','../products/253/02-verde.png','../products/253/03-transparente.png','../products/253/04-laranja.png','../products/253/05-marrom.png','../products/253/06-preto.png'], ml:ICEMAN_ML, shopee:ICEMAN_SHOPEE },
  { id:'586B', name:'ICEMAN 586B', label:'Luz azul • Meio aro', description:'Modelo único de armação meio aro com lentes transparentes e filtro de luz azul.', details:['Filtro de luz azul','Lentes transparentes','Formato meio aro','Modelo único'], colors:[{name:'Preto',hex:'#111315',image:'../products/586B/01-principal.png'}], images:['../products/586B/01-principal.png','../products/586B/02-frontal.jpg','../products/586B/03-medidas.jpg','../products/586B/04-teste-luz-azul.jpg'], ml:ICEMAN_ML, shopee:ICEMAN_SHOPEE },
  { id:'474', name:'ICEMAN 474', label:'Polarizado • Esportivo', description:'Armação metálica retangular, leve e marcante, com oito variações de acabamento.', details:['Lentes polarizadas','Proteção UV400','Armação metálica','8 variações de cor'], colors:[{name:'Amarelo',hex:'#ead748',image:'../products/474/08-amarelo.png'},{name:'Verde / Dourado',hex:'#71806c',image:'../products/474/07-verde-dourado.png'},{name:'Cinza Chumbo',hex:'#555b60',image:'../products/474/06-fotocromico.png'},{name:'Preto',hex:'#111315',image:'../products/474/05-preto.png'},{name:'Marrom',hex:'#9a633f',image:'../products/474/04-marrom.png'},{name:'Prateado Espelhado',hex:'#c6cbd0',image:'../products/474/01-prateado-espelhado.png'},{name:'Azul Espelhado',hex:'#26a8d8',image:'../products/474/02-azul-espelhado.png'},{name:'Fotocromático',hex:'#737a80',image:'../products/474/03-cinza-chumbo.png'}], images:['../products/474/05-preto.png','../products/474/08-amarelo.png','../products/474/07-verde-dourado.png','../products/474/06-fotocromico.png','../products/474/04-marrom.png','../products/474/01-prateado-espelhado.png','../products/474/02-azul-espelhado.png','../products/474/03-cinza-chumbo.png'], ml:ICEMAN_ML, shopee:ICEMAN_SHOPEE },
  { id:'881F', name:'ICEMAN 881F', label:'Fotocromático • Quadrado', description:'Armação quadrada contemporânea com lentes adaptáveis à luminosidade e três acabamentos.', details:['Lentes fotocromáticas','Proteção UV400','Armação leve','3 variações de cor'], colors:[{name:'Preto',hex:'#111315',image:'../products/881F/03-preto.png'},{name:'Preto / Prateado',hex:'#92989e',image:'../products/881F/02-preto-prateado.png'},{name:'Cinza / Prateado Transparente',hex:'#aeb4b9',image:'../products/881F/01-cinza-prateado-transparente.png'}], images:['../products/881F/03-preto.png','../products/881F/02-preto-prateado.png','../products/881F/01-cinza-prateado-transparente.png'], ml:ICEMAN_ML, shopee:ICEMAN_SHOPEE },
  { id:'989F', name:'ICEMAN 989F', label:'Fotocromático • Meio aro', description:'Armação metálica leve, perfil técnico e lentes adaptáveis à luminosidade.', details:['Lentes fotocromáticas','Proteção UV400','Armação metálica','3 variações de cor'], colors:[{name:'Prateado',hex:'#c0c5c9',image:'../products/989F/01-prateado.png'},{name:'Cinza',hex:'#676b70',image:'../products/989F/02-cinza.png'},{name:'Preto',hex:'#111315',image:'../products/989F/03-preto.png'}], images:['../products/989F/01-prateado.png','../products/989F/02-cinza.png','../products/989F/03-preto.png'], ml:ICEMAN_ML, shopee:ICEMAN_SHOPEE },
  { id:'834', name:'ICEMAN 834', label:'Polarizado • Redondo', description:'Formato redondo compacto com cinco combinações de armação e lentes.', details:['Lentes polarizadas','Proteção UV400','Formato redondo','5 variações de cor'], colors:[{name:'Marrom',hex:'#8b572f',image:'../products/834/01-marrom.png'},{name:'Transparente',hex:'#d9dde0',image:'../products/834/02-transparente.png'},{name:'Preto',hex:'#111315',image:'../products/834/03-preto.png'},{name:'Verde',hex:'#536b59',image:'../products/834/04-verde.png'},{name:'Amarelo',hex:'#e7c84e',image:'../products/834/05-amarelo.png'}], images:['../products/834/01-marrom.png','../products/834/02-transparente.png','../products/834/03-preto.png','../products/834/04-verde.png','../products/834/05-amarelo.png'], ml:ICEMAN_ML, shopee:ICEMAN_SHOPEE },
  { id:'476', name:'ICEMAN INFANTIL', label:'Infantil • Flexível', description:'Óculos infantil leve e confortável, com proteção UV400 e treze combinações de cores.', details:['Proteção UV400','Armação leve e flexível','Formato infantil','13 variações de cor'], colors:[{name:'Azul / Amarelo',hex:'#17a9df',image:'../products/infantil/01-azul-amarelo.png'},{name:'Preto Brilhante',hex:'#101214',image:'../products/infantil/02-preto-brilhante.png'},{name:'Preto / Vermelho',hex:'#e82c31',image:'../products/infantil/03-preto-vermelho.png'},{name:'Rosa / Verde',hex:'#f281ae',image:'../products/infantil/04-rosa-verde.png'},{name:'Preto Fosco',hex:'#242628',image:'../products/infantil/05-preto-fosco.png'},{name:'Verde',hex:'#9ebc37',image:'../products/infantil/06-verde.png'},{name:'Vermelho / Preto',hex:'#ef3635',image:'../products/infantil/07-vermelho-preto.png'},{name:'Rosa Escuro / Rosa Claro',hex:'#ee5478',image:'../products/infantil/08-rosa-escuro-rosa-claro.png'},{name:'Azul / Rosa',hex:'#40bfe7',image:'../products/infantil/09-azul-rosa.png'},{name:'Rosa Claro',hex:'#f3a1aa',image:'../products/infantil/10-rosa-claro.png'},{name:'Azul Escuro / Azul Claro',hex:'#245fc4',image:'../products/infantil/11-azul-escuro-azul-claro.png'},{name:'Preto / Azul',hex:'#249ed5',image:'../products/infantil/12-preto-azul.png'},{name:'Rosa / Lilás',hex:'#c58ec9',image:'../products/infantil/13-rosa-lilas.png'}], images:['../products/infantil/01-azul-amarelo.png','../products/infantil/02-preto-brilhante.png','../products/infantil/03-preto-vermelho.png','../products/infantil/04-rosa-verde.png','../products/infantil/05-preto-fosco.png','../products/infantil/06-verde.png','../products/infantil/07-vermelho-preto.png','../products/infantil/08-rosa-escuro-rosa-claro.png','../products/infantil/09-azul-rosa.png','../products/infantil/10-rosa-claro.png','../products/infantil/11-azul-escuro-azul-claro.png','../products/infantil/12-preto-azul.png','../products/infantil/13-rosa-lilas.png'], ml:ICEMAN_ML, shopee:ICEMAN_SHOPEE },
  { id:'ciclismo', name:'ICEMAN CICLISMO', label:'Esportivo • Ciclismo', description:'Óculos esportivo de lente ampla para proteção, conforto e visão panorâmica em movimento.', details:['Proteção UV400','Lente panorâmica','Encaixe esportivo','5 variações'], colors:[{name:'Preto',hex:'#111315',image:'../products/ciclismo/01-preto.png'},{name:'Azul Claro',hex:'#28aee8',image:'../products/ciclismo/02-azul-claro.png'},{name:'Azul Escuro',hex:'#244e9f',image:'../products/ciclismo/03-azul-escuro.png'},{name:'Roxo',hex:'#8651cc',image:'../products/ciclismo/04-roxo.png'},{name:'Fotocromático',hex:'#a8adb2',image:'../products/ciclismo/05-fotocromatico.png'}], images:['../products/ciclismo/02-azul-claro.png','../products/ciclismo/01-preto.png','../products/ciclismo/03-azul-escuro.png','../products/ciclismo/04-roxo.png','../products/ciclismo/05-fotocromatico.png'], ml:ICEMAN_ML, shopee:ICEMAN_SHOPEE }
]};

window.ICEMAN_CATALOG.products.forEach((product) => {
  product.ml = ICEMAN_ML_PRODUCTS[product.id] || ICEMAN_ML;
  product.shopee = ICEMAN_SHOPEE_PRODUCTS[product.id] || ICEMAN_SHOPEE;
});
